# Generated by Django 3.2.9 on 2022-12-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='cover_image',
        ),
    ]
