# Generated by Django 3.2.9 on 2022-12-19 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20221219_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='aciklama',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='urun',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='UrunFotograf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.urun')),
            ],
        ),
    ]
