# Generated by Django 3.2.9 on 2022-12-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221219_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='urun',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
