# Generated by Django 3.2.9 on 2022-12-19 19:35

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20221219_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='fiyat',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='TL', max_digits=10),
        ),
    ]
