# Generated by Django 3.2.9 on 2022-12-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_urun_fiyat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urun',
            old_name='isim',
            new_name='name',
        ),
    ]
