# Generated by Django 3.2.9 on 2022-12-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_isim_urun_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urunfotograf',
            name='urun',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='image',
        ),
        migrations.AddField(
            model_name='urun',
            name='image',
            field=models.ManyToManyField(to='main.UrunFotograf'),
        ),
        migrations.AlterField(
            model_name='urunfotograf',
            name='image',
            field=models.ImageField(upload_to='urunler'),
        ),
    ]
