# Generated by Django 3.2.9 on 2022-12-22 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20221222_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sehirler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sehir_adi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres_adi', models.CharField(max_length=50)),
                ('adres', models.TextField(max_length=400)),
                ('sehir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sehirler')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
