# Generated by Django 3.2.9 on 2022-12-23 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_yorum_yorumfotograf'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='yorum_urun',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.urun'),
        ),
    ]
