# Generated by Django 3.2.9 on 2022-12-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_creditcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='kard_numarasi',
            new_name='card_number',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='son_kullanma_tarihi',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='expiration_date_month',
            field=models.CharField(default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='expiration_date_year',
            field=models.CharField(default=24, max_length=2),
        ),
    ]
