# Generated by Django 3.2.9 on 2022-12-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_siparis_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='durum',
            field=models.CharField(choices=[('onay_bekliyor', 'Onay Bekliyor'), ('kargolandi', 'Kargolandı'), ('teslim_edildi', 'Teslim Edildi'), ('iade_edildi', 'İade Edildi')], default='onay_bekliyor', max_length=50),
        ),
    ]
