# Generated by Django 3.2.9 on 2022-12-27 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0019_alter_siparis_durum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siparisurun',
            old_name='tutar',
            new_name='fiyat',
        ),
        migrations.RenameField(
            model_name='siparisurun',
            old_name='tutar_currency',
            new_name='fiyat_currency',
        ),
        migrations.AddField(
            model_name='siparis',
            name='first_name',
            field=models.CharField(default='no-name', max_length=10),
        ),
        migrations.AddField(
            model_name='siparis',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='siparis',
            name='last_name',
            field=models.CharField(default='no-name', max_length=10),
        ),
        migrations.AddField(
            model_name='siparis',
            name='telefon',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='siparisurun',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
