# Generated by Django 3.2.9 on 2022-12-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20221227_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparisurun',
            name='can_comment',
            field=models.BooleanField(default=False),
        ),
    ]
