# Generated by Django 3.2.9 on 2022-12-27 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_siparisurun_can_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siparisurun',
            name='can_comment',
        ),
        migrations.RemoveField(
            model_name='siparisurun',
            name='status',
        ),
    ]
